// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg65WtA5TKHaHS1WRrLBI06gMLWduNH_U',
    appId: '1:273818399107:web:b548d9f16b3eb3c66c06b6',
    messagingSenderId: '273818399107',
    projectId: 'health-care-faooex',
    authDomain: 'health-care-faooex.firebaseapp.com',
    storageBucket: 'health-care-faooex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNe4aGTtY7uu5TLIevExq5u8hAourWKaY',
    appId: '1:273818399107:android:4375837b530129106c06b6',
    messagingSenderId: '273818399107',
    projectId: 'health-care-faooex',
    storageBucket: 'health-care-faooex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGyIBsVd1S_JzLZDVJy02k-2HwJ6JJtc',
    appId: '1:273818399107:ios:7dfaa353ffa891996c06b6',
    messagingSenderId: '273818399107',
    projectId: 'health-care-faooex',
    storageBucket: 'health-care-faooex.firebasestorage.app',
    iosBundleId: 'com.example.zomatoRestaurent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGyIBsVd1S_JzLZDVJy02k-2HwJ6JJtc',
    appId: '1:273818399107:ios:7dfaa353ffa891996c06b6',
    messagingSenderId: '273818399107',
    projectId: 'health-care-faooex',
    storageBucket: 'health-care-faooex.firebasestorage.app',
    iosBundleId: 'com.example.zomatoRestaurent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGTa9qdJsQcMPVIoppf5MXPj3yZsx6jI',
    appId: '1:273818399107:web:254017e9b1aa05956c06b6',
    messagingSenderId: '273818399107',
    projectId: 'health-care-faooex',
    authDomain: 'health-care-faooex.firebaseapp.com',
    storageBucket: 'health-care-faooex.firebasestorage.app',
  );
}
