name: Flutter macOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'   # ✅ specify exact version
          channel: 'stable'           # ✅ specify channel explicitly
          architecture: x64           # ✅ use x64 for better compatibility

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos
