name: Flutter macOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('.github/workflows/flutter_macos.yml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'   # ✅ includes Dart 3.9+
          channel: 'stable'
          architecture: x64

      # Cache Dart & pub packages
      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos
